### ISSUE TITLE
How to fix login command.

### ISSUE THREAD

**Issue by Artforlfmj** [RiftSTW/carbide-src#1]
How can i fix the login command?

**Comment by Artlfmj** [comment]
I’m trying to adapt it it’s different. It helps me learn

**Comment by RiftSTW** [comment]
Use the dauntless token (YjA3MGYyMDcyOWY4NDY5M2I1ZDYyMWM5MDRmYzViYzI6SEdAWEUmVEdDeEVKc2dUIyZfcDJdPWFSbyN+Pj0+K2M2UGhSKXpYUA) to generate the device auth/code and use the switch token for the rest

**Comment by RiftSTW** [comment]
> bruh u trying to skid a wrong source code

I'm pretty sure tornado is just saying that to get people not to use it but this was the source code that tornado had uploaded before he added the paywall

**Comment by NanosaysHi** [comment]
> > bruh u trying to skid a wrong source code
> 
> I'm pretty sure tornado is just saying that to get people not to use it but this was the source code that tornado had uploaded before he added the paywall

tornado said that his source is in c#

**Comment by RiftSTW** [comment]
> > > bruh u trying to skid a wrong source code
> > 
> > 
> > I'm pretty sure tornado is just saying that to get people not to use it but this was the source code that tornado had uploaded before he added the paywall
> 
> tornado said that his source is in c#

Yeah prolly the new source for carbide

**Comment by NanosaysHi** [comment]
> > > > bruh u trying to skid a wrong source code
> > > 
> > > 
> > > I'm pretty sure tornado is just saying that to get people not to use it but this was the source code that tornado had uploaded before he added the paywall
> > 
> > 
> > tornado said that his source is in c#
> 
> Yeah prolly the new source for carbide

he didnt change it after u sent, he told me abt that from  more than a month
